from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
if '/* v20.3 auto contrast */' in s: raise SystemExit(0)
patch=r'''
<style id="v203-auto">/* v20.3 auto contrast */
.v203ColorBox{margin-top:12px;padding-top:11px;border-top:1px solid var(--xline)}.v203ColorRow{display:grid;grid-template-columns:44px 1fr auto;gap:8px;align-items:center;margin-top:7px}#v203BgColor{width:44px;height:38px;padding:2px;border-radius:9px;cursor:pointer}#v203ColorValue{font-size:11px;font-weight:800;color:var(--xmuted)}
</style><script>
(function(){const TK='champ_ui_theme_v202',CK='champ_ui_custom_bg_v203',R=document.documentElement;const rgb=h=>{h=h.replace('#','');return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16))},hx=a=>'#'+a.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join(''),mix=(a,t,p)=>a.map((v,i)=>v+(t[i]-v)*p),lum=a=>{a=a.map(v=>{v/=255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4});return .2126*a[0]+.7152*a[1]+.0722*a[2]};
const vars=['--xbg','--xtop','--xcard','--xcard2','--xline','--xtext','--xmuted','--xsoft','--xaccent','--xaccenttext'];
function clear(){vars.forEach(k=>R.style.removeProperty(k));R.style.removeProperty('color-scheme')}
function apply(h,save=true){const a=rgb(h),d=lum(a)<.38,w=[255,255,255],b=[0,0,0];R.dataset.appTheme='custom';R.style.setProperty('--xbg',h);R.style.setProperty('--xtop',hx(mix(a,d?w:b,.04)));R.style.setProperty('--xcard',hx(mix(a,d?w:b,d?.10:.055)));R.style.setProperty('--xcard2',hx(mix(a,d?w:b,d?.16:.095)));R.style.setProperty('--xline',hx(mix(a,d?w:b,d?.28:.20)));R.style.setProperty('--xsoft',hx(mix(a,d?w:b,d?.20:.13)));R.style.setProperty('--xtext',d?'#f4f7fb':'#16191e');R.style.setProperty('--xmuted',d?'#aab4c2':'#5f6874');R.style.setProperty('--xaccent',d?'#eef2f7':'#20242a');R.style.setProperty('--xaccenttext',d?'#15181c':'#fff');R.style.colorScheme=d?'dark':'light';if(save){localStorage.setItem(TK,'custom');localStorage.setItem(CK,h)}document.querySelectorAll('.v202ThemeGrid button').forEach(x=>x.classList.remove('active'));const o=document.getElementById('v203ColorValue');if(o)o.textContent=h.toUpperCase()+(d?' ・ 白文字':' ・ 黒文字')}
function mount(){const p=document.getElementById('v202SettingsPanel'),g=p?.querySelector('.v202ThemeGrid');if(!p||!g||document.getElementById('v203BgColor'))return;g.querySelectorAll('[data-t]').forEach(x=>x.addEventListener('click',clear,true));const box=document.createElement('div');box.className='v203ColorBox';box.innerHTML='<div class="small"><b>背景色を自由に変更</b><br>文字色は自動で見やすく調整します。</div><div class="v203ColorRow"><input id="v203BgColor" type="color"><span id="v203ColorValue"></span><button type="button" id="v203ResetColor">標準へ</button></div>';p.appendChild(box);const c=box.querySelector('#v203BgColor');c.value=localStorage.getItem(CK)||'#252a31';c.oninput=()=>apply(c.value);box.querySelector('#v203ResetColor').onclick=()=>{clear();window.v202SetTheme?.('charcoal')};if(localStorage.getItem(TK)==='custom')apply(c.value,false)}mount();setTimeout(mount,0);window.v203ApplyCustomTheme=apply})();
</script>'''
s=s.replace('</body>',patch+'\n</body>',1);p.write_text(s,encoding='utf-8')
