from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
marker='/* ===== v20.4 sidebar styles ===== */'
if marker in s: raise SystemExit(0)
s=s.replace('Pokémon Champions Support — v20.2','Pokémon Champions Support — v20.4').replace('Pokémon Champions Support — v20.3','Pokémon Champions Support — v20.4')
s=s.replace('<div class="badge">v18 USEFUL</div>','<div class="badge">v20.4</div>',1)
css=r'''<style id="v204-sidebar-style">
/* ===== v20.4 sidebar styles ===== */
:root{--v204-side:214px;--v204-mini:72px}#v204Sidebar{display:none}
@media(min-width:1080px){body.v204HasSidebar .wrap{width:auto!important;max-width:none!important;margin:0!important;padding:14px 22px 28px 242px!important;transition:padding-left .18s}body.v204HasSidebar.v204SideMini .wrap{padding-left:100px!important}body.v204HasSidebar>.wrap>header{max-width:1080px;margin:0 auto 10px!important;min-height:44px}body.v204HasSidebar>.wrap>header h1{font-size:24px!important}body.v204HasSidebar>.wrap>header .sub{font-size:10px!important}body.v204HasSidebar>.wrap>.appnav{display:none!important}#v204Sidebar{display:flex;position:fixed;z-index:420;left:12px;top:12px;bottom:12px;width:var(--v204-side);padding:12px;flex-direction:column;gap:8px;background:var(--xcard,#111722);border:1px solid var(--xline,#2a3548);border-radius:18px;box-shadow:0 16px 42px #0003;color:var(--xtext,#f7f8fb);transition:width .18s,padding .18s}body.v204SideMini #v204Sidebar{width:var(--v204-mini);padding:9px}}
.v204SideTop{display:flex;align-items:center;gap:8px;padding:4px 3px 8px;border-bottom:1px solid var(--xline,#2a3548)}.v204Mark{width:36px;height:36px;flex:0 0 36px;border-radius:11px;display:grid;place-items:center;background:var(--xaccent,#6da7ff);color:var(--xaccenttext,#fff);font-size:14px;font-weight:950}.v204Brand{min-width:0;line-height:1.05}.v204Brand b{display:block;font-size:12px}.v204Brand span{font-size:8px;color:var(--xmuted,#9aa7ba)}.v204Collapse{margin-left:auto!important;width:30px!important;height:30px!important;min-height:30px!important;padding:0!important;border-radius:9px!important}.v204SectionTitle{font-size:8px;font-weight:900;letter-spacing:.14em;color:var(--xmuted,#9aa7ba);padding:5px 7px 1px}.v204Nav{display:grid;gap:3px}.v204NavBtn,.v204QuickBtn{width:100%;min-height:38px!important;padding:7px 8px!important;display:grid!important;grid-template-columns:24px minmax(0,1fr) auto;align-items:center;gap:7px;text-align:left!important;border-radius:10px!important;background:transparent!important;box-shadow:none!important;color:var(--xmuted,#9aa7ba)!important}.v204NavBtn:hover,.v204QuickBtn:hover{background:var(--xsoft,#24324b)!important;color:var(--xtext,#f7f8fb)!important}.v204NavBtn.active{background:var(--xaccent,#6da7ff)!important;color:var(--xaccenttext,#fff)!important}.v204I{width:21px;height:21px;display:grid;place-items:center}.v204I svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.v204Txt{font-size:10px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v204Badge{font-size:8px;font-weight:900;min-width:26px;text-align:center;padding:2px 5px;border-radius:999px;border:1px solid currentColor;opacity:.76}.v204SideStatus{padding:9px;border:1px solid var(--xline,#2a3548);border-radius:12px;background:var(--xcard2,#0d141f)}.v204StatusHead{display:flex;justify-content:space-between;font-size:9px;font-weight:900;margin-bottom:7px}.v204StatusGrid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.v204StatMini{padding:6px;border-radius:8px;background:var(--xcard,#111722);border:1px solid var(--xline,#2a3548)}.v204StatMini span{display:block;font-size:7px;color:var(--xmuted,#9aa7ba)}.v204StatMini b{font-size:13px}.v204Progress{height:5px;border-radius:999px;background:var(--xsoft,#24324b);overflow:hidden;margin-top:7px}.v204Progress>i{display:block;height:100%;background:var(--xaccent,#6da7ff)}.v204SideBottom{margin-top:auto;display:grid;gap:4px}.v204ThemeName{font-size:8px;color:var(--xmuted,#9aa7ba);padding:0 7px}.v204SideMini .v204Brand,.v204SideMini .v204SectionTitle,.v204SideMini .v204Txt,.v204SideMini .v204Badge,.v204SideMini .v204SideStatus,.v204SideMini .v204ThemeName{display:none!important}.v204SideMini .v204Mark{display:none}.v204SideMini .v204Collapse{margin:auto!important}.v204SideMini .v204NavBtn,.v204SideMini .v204QuickBtn{grid-template-columns:1fr!important;padding:7px!important}.v204SideMini .v204I{margin:auto}
#homePage{max-width:1040px;margin-left:auto;margin-right:auto}#homePage .homeHeroV18{grid-template-columns:minmax(0,1fr) 170px!important;gap:12px!important;padding:15px 16px!important;align-items:center!important;background:var(--xcard,#111722)!important}#homePage .homeHeroCopy{min-height:104px!important}#homePage .homeHeroCopy h2{font-size:clamp(22px,2.4vw,30px)!important;margin:3px 0 5px!important}#homePage .homeEyebrow{font-size:8px!important}#homePage .homeLead{font-size:11px!important;line-height:1.5!important}#homePage .homeActions{margin-top:10px!important;gap:6px!important}#homePage .homeActions button{min-height:34px!important;padding:7px 10px!important;font-size:10px!important}#homePage .homeScorePanel{padding:11px!important;border-radius:13px!important;min-height:104px!important}#homePage .homeSetupScore{font-size:34px!important;margin:1px 0!important}#homePage .homeGridV18{grid-template-columns:1.12fr .88fr!important;gap:11px!important}#homePage .card{border-radius:15px!important;padding:13px!important;margin-bottom:11px!important}#homePage .homePanelV18{margin-bottom:11px!important}#homePage .homePartyPreview{gap:5px!important;margin:9px 0 5px!important}#homePage .homePartyMon,#homePage .homePartyEmpty{min-height:82px!important;border-radius:10px!important;padding:4px!important}#homePage .homePartyMon img{width:48px!important;height:48px!important}#homePage .homeToolGrid{gap:6px!important;margin-top:8px!important}#homePage .homeTool{min-height:62px!important;padding:9px!important;border-radius:10px!important}#homePage .homeTool b{font-size:11px!important}#homePage .homeTool span{font-size:8px!important}#homePage .homeMetaTop{gap:6px!important;margin-top:9px!important}#homePage .homeMetaMon{border-radius:10px!important;padding:6px!important}#homePage .homeMetaMon img{width:50px!important;height:50px!important}@media(max-width:720px){#homePage .homeHeroV18,#homePage .homeGridV18{grid-template-columns:1fr!important}}
</style>'''
s=s.replace('</body>',css+'\n</body>',1);p.write_text(s,encoding='utf-8')
