from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
marker='/* ===== v20.5 party workflow + rail ===== */'
if marker in s: raise SystemExit(0)
js=r'''<script>
/* ===== v20.5 party workflow + rail ===== */
(function(){
'use strict';
const icons={home:'<path d="M4 10 12 4l8 6"/><path d="M6 9v11h12V9"/>',quick:'<path d="m13 2-7 11h6l-1 9 7-12h-6l1-8Z"/>',party:'<circle cx="8" cy="8" r="3"/><circle cx="16" cy="8" r="3"/><path d="M3 20c.5-4 2.3-6 5-6s4.5 2 5 6"/><path d="M12 20c.4-3.6 1.8-5.5 4-5.5 2.4 0 4 1.9 4.5 5.5"/>',env:'<path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A7 7 0 0 0 15 6l-.3-2.6h-4L10.5 6A7 7 0 0 0 9 7.1l-2.4-1-2 3.4 2 1.5a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1A7 7 0 0 0 10.5 18l.3 2.6h4L15 18a7 7 0 0 0 1.5-1.1l2.4 1 2-3.4-2-1.5c.1-.3.1-.7.1-1Z"/>'};
const svg=k=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[k]}</svg>`;
const move=x=>typeof x==='string'?{name:x,type:'変化'}:(x&&typeof x==='object'?{...x}:{name:'',type:'変化'});
function pcount(){try{return (savedParty||[]).length}catch(e){return 0}}
function activePage(){return [...document.querySelectorAll('.page.activePage')][0]?.id?.replace(/Page$/,'')||'home'}
function railActive(){const p=activePage();document.querySelectorAll('#v205Rail [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const c=document.querySelector('#v205Rail [data-count]');if(c)c.textContent=pcount()}
function openSettings(){const p=document.getElementById('v202SettingsPanel');if(p)p.classList.add('show');else document.getElementById('v202SettingsBtn')?.click()}
function rail(){if(document.getElementById('v205Rail'))return;document.getElementById('v204Sidebar')?.remove();document.body.classList.add('v205RailOn');const a=document.createElement('aside');a.id='v205Rail';a.innerHTML=`<div class="v205Logo">CS</div><div class="v205RailSep"></div><button class="v205RailBtn" data-page="home">${svg('home')}<span class="v205Tip">ホーム</span></button><button class="v205RailBtn" data-page="quick">${svg('quick')}<span class="v205Tip">クイック選出</span></button><button class="v205RailBtn" data-page="party">${svg('party')}<span class="v205Tip">パーティ</span><span class="v205Count" data-count>0</span></button><button class="v205RailBtn" data-page="env">${svg('env')}<span class="v205Tip">環境データ</span></button><div class="v205RailBottom"><button class="v205RailBtn" data-settings>${svg('settings')}<span class="v205Tip">表示設定</span></button></div>`;document.body.appendChild(a);a.querySelector('[data-page=home]').onclick=()=>switchPage('home');a.querySelector('[data-page=quick]').onclick=()=>switchPage('quick');a.querySelector('[data-page=party]').onclick=()=>v205OpenParty();a.querySelector('[data-page=env]').onclick=()=>switchPage('env');a.querySelector('[data-settings]').onclick=openSettings;railActive()}
function migrate(){try{if((savedParty||[]).length===0&&(buildTeam||[]).length){savedParty=buildTeam.slice(0,6).map(m=>({...m,item:buildItems?.[m.name]||m?.set?.item||'',moves:Array.from({length:4},(_,i)=>move(m?.set?.moves?.[i]))}));saveSavedParty?.()}for(const sp of (savedParty||[])){const b=(buildTeam||[]).find(x=>x?.name===sp?.name);if(!b)continue;if(!String(sp.item||'').trim())sp.item=buildItems?.[b.name]||b?.set?.item||'';if(!(sp.moves||[]).some(x=>x?.name)&&(b?.set?.moves||[]).some(x=>x?.name))sp.moves=Array.from({length:4},(_,i)=>move(b.set.moves?.[i]))}saveSavedParty?.()}catch(e){console.warn('v20.5 migrate',e)}}
let sig='';
function signature(){try{return JSON.stringify((savedParty||[]).map(m=>[m.name,m.item,(m.moves||[]).map(x=>x?.name||''),m.customRole||m.role||'']))}catch(e){return ''}}
function sync(force=false){const n=signature();if(!force&&n===sig)return;sig=n;try{const team=[],items={};for(const sp of (savedParty||[]).slice(0,6)){const base=(mons||[]).find(x=>x.name===sp.name)||sp,ms=Array.from({length:4},(_,i)=>move(sp.moves?.[i]));const m={...base,role:sp.customRole||sp.role||base.role,set:{...(base.set||{}),item:String(sp.item||''),moves:ms}};team.push(m);items[m.name]=m.mega?(typeof megaStoneFor==='function'?megaStoneFor(m):String(sp.item||'')):String(sp.item||'')}buildTeam=team;buildItems=items;localStorage.setItem('champ_build',JSON.stringify(buildTeam));localStorage.setItem('champ_build_items',JSON.stringify(buildItems));try{V12_PROFILE_CACHE.clear()}catch(e){};try{renderBuildCurrent()}catch(e){};railActive()}catch(e){console.warn('v20.5 sync',e)}}
function partyPage(){if(document.getElementById('partyPage'))return;const saved=document.getElementById('savedPage'),build=document.getElementById('buildPage'),env=document.getElementById('envPage');if(!saved||!build||!env)return;const p=document.createElement('div');p.id='partyPage';p.className='page';p.innerHTML=`<section class="card v205PartyHead"><div><h2>パーティ</h2><div class="small">6体・持ち物・4技をここで管理。そのまま選出と構築分析に使います。</div></div><div class="v205PartyActions"><button onclick="loadSavedToQuick()">この6体で選出</button><button class="primary" onclick="v205AnalyzeParty()">総合分析</button></div></section><div class="v205PartyTabs"><button class="v205PartyTab active" data-party-tab="edit">編集</button><button class="v205PartyTab" data-party-tab="analysis">分析・対策</button></div><div id="v205PartyEdit" class="v205PartyPane active"></div><div id="v205PartyAnalysis" class="v205PartyPane"></div>`;env.parentNode.insertBefore(p,env);const edit=p.querySelector('#v205PartyEdit'),analysis=p.querySelector('#v205PartyAnalysis');[...saved.children].forEach(x=>edit.appendChild(x));const first=edit.querySelector('.card');if(first){first.querySelector('h2')&&(first.querySelector('h2').textContent='6体と型を編集');const d=first.querySelector('.small');if(d)d.textContent='ここで登録した内容がクイック選出と構築分析の共通データになります。'}const tool=document.createElement('section');tool.className='card';tool.id='v205PartyAnalysisToolbar';tool.innerHTML='<div><b>構築分析・対策</b><div class="small">編集した6体と現在の技・持ち物をそのまま使用します。</div></div><div class="v205AnalysisBtns"><button class="primary" onclick="v205AnalyzeParty()">総合提案を更新</button><button onclick="document.getElementById(\'counterPokemonInput\')?.focus()">苦手を入力</button></div>';analysis.appendChild(tool);document.getElementById('counterTool')&&analysis.appendChild(document.getElementById('counterTool'));document.getElementById('buildResult')&&analysis.appendChild(document.getElementById('buildResult'));saved.style.display='none';build.style.display='none';p.querySelectorAll('[data-party-tab]').forEach(b=>b.onclick=()=>v205PartyTab(b.dataset.partyTab));document.querySelectorAll('.appnav button').forEach(b=>{const on=b.getAttribute('onclick')||'';if(on.includes("'saved'")||on.includes('"saved"')){b.textContent='パーティ';b.setAttribute('onclick','v205OpenParty()')}else if(on.includes("'build'")||on.includes('"build"'))b.style.display='none'})}
window.v205PartyTab=function(t='edit'){document.querySelectorAll('.v205PartyPane').forEach(x=>x.classList.toggle('active',x.id===(t==='analysis'?'v205PartyAnalysis':'v205PartyEdit')));document.querySelectorAll('.v205PartyTab').forEach(x=>x.classList.toggle('active',x.dataset.partyTab===t));try{localStorage.setItem('champ_v205_party_tab',t)}catch(e){}};
window.v205OpenParty=function(t){partyPage();sync(true);document.querySelectorAll('.page').forEach(x=>x.classList.remove('activePage'));document.getElementById('partyPage')?.classList.add('activePage');try{t=t||localStorage.getItem('champ_v205_party_tab')||'edit'}catch(e){t=t||'edit'}v205PartyTab(t);try{renderSavedEditors();renderSavedRoster();renderSavedCompletion()}catch(e){}railActive();window.scrollTo(0,0)};
window.v205AnalyzeParty=function(){sync(true);v205OpenParty('analysis');setTimeout(()=>{try{analyzeBuild()}catch(e){console.error(e)}},0)};
migrate();partyPage();sync(true);rail();const oldSwitch=window.switchPage;if(typeof oldSwitch==='function'){window.switchPage=function(name){if(name==='saved')return v205OpenParty('edit');if(name==='build'||name==='party')return v205OpenParty(name==='build'?'analysis':undefined);const r=oldSwitch.apply(this,arguments);setTimeout(railActive,0);return r}}
if(typeof window.addBuild==='function'){const oldAdd=window.addBuild;window.addBuild=function(name){if(document.getElementById('partyPage')){addSaved(name);sync(true);v205OpenParty('edit');return}return oldAdd.apply(this,arguments)}}
if(typeof window.analyzeBuild==='function'){const oldAnalyze=window.analyzeBuild;window.analyzeBuild=function(){sync(true);return oldAnalyze.apply(this,arguments)}}if(typeof window.analyzeCounterPokemon==='function'){const oldCounter=window.analyzeCounterPokemon;window.analyzeCounterPokemon=function(){sync(true);return oldCounter.apply(this,arguments)}}setInterval(()=>{if(signature()!==sig)sync(true);railActive()},700);new MutationObserver(railActive).observe(document.documentElement,{attributes:true,attributeFilter:['data-app-theme']});window.__V205_TEST__={party:!!document.getElementById('partyPage'),rail:!!document.getElementById('v205Rail')};
})();
</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')
