from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
marker='/* ===== v20.4 sidebar behavior ===== */'
if marker in s: raise SystemExit(0)
js=r'''<script>
/* ===== v20.4 sidebar behavior ===== */
(function(){
const K='champ_v204_side_mini';
const ico={home:'⌂',quick:'⚡',saved:'▣',build:'◇',env:'▥',target:'◎',back:'‹',settings:'⚙'};
function stat(){const t=window.savedParty||[],done=t.filter(m=>String(m.item||'').trim()&&(m.moves||[]).filter(x=>x?.name).length===4).length,mega=t.filter(m=>m?.mega).length,pct=Math.round((t.length/6*.45+done/6*.55)*100);return{n:t.length,done,mega,pct}}
function page(){const p=[...document.querySelectorAll('.page')].find(x=>x.classList.contains('activePage'));return p?.id?.replace(/Page$/,'')||'home'}
function openSettings(){const p=document.getElementById('v202SettingsPanel');if(p)p.classList.add('show');else document.getElementById('v202SettingsBtn')?.click()}
function refresh(){const a=document.getElementById('v204Sidebar');if(!a)return;const x=stat();a.querySelector('[data-party]').textContent=x.n+'/6';a.querySelector('[data-ready]').textContent=x.pct+'%';a.querySelector('[data-n]').textContent=x.n+'/6';a.querySelector('[data-done]').textContent=x.done+'/6';a.querySelector('[data-mega]').textContent=x.mega;a.querySelector('[data-build]').textContent=(window.buildTeam||[]).length+'/6';a.querySelector('[data-bar]').style.width=x.pct+'%';a.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page()));const t=document.documentElement.dataset.appTheme||'charcoal';a.querySelector('[data-theme]').textContent='テーマ：'+({classic:'クラシック',charcoal:'チャコール',light:'ライト',dark:'ダーク',teal:'ティール',custom:'カスタム'}[t]||t)}
function btn(kind,label,badge=''){return `<button class="v204NavBtn" data-page="${kind}"><span class="v204I">${ico[kind]}</span><span class="v204Txt">${label}</span>${badge?`<span class="v204Badge" ${badge}>0/6</span>`:''}</button>`}
function q(action,kind,label){return `<button class="v204QuickBtn" data-action="${action}"><span class="v204I">${ico[kind]}</span><span class="v204Txt">${label}</span></button>`}
function make(){if(document.getElementById('v204Sidebar'))return;document.body.classList.add('v204HasSidebar');try{if(localStorage.getItem(K)==='1')document.body.classList.add('v204SideMini')}catch(e){};const a=document.createElement('aside');a.id='v204Sidebar';a.innerHTML=`<div class="v204SideTop"><div class="v204Mark">CS</div><div class="v204Brand"><b>Champions</b><span>Support v20.4</span></div><button class="v204Collapse" title="縮める">‹</button></div><div class="v204SectionTitle">MAIN</div><div class="v204Nav">${btn('home','ホーム')}${btn('quick','クイック選出')}${btn('saved','パーティ登録','data-party')}${btn('build','パーティ構築')}${btn('env','環境データ')}</div><div class="v204SectionTitle">QUICK</div><div class="v204Nav">${q('savedQuick','quick','登録6体で選出')}${q('counter','target','苦手ポケモン対策')}${q('back','back','前のページ')}</div><div class="v204SideStatus"><div class="v204StatusHead"><span>準備状況</span><b data-ready>0%</b></div><div class="v204StatusGrid"><div class="v204StatMini"><span>登録</span><b data-n>0/6</b></div><div class="v204StatMini"><span>型完成</span><b data-done>0/6</b></div><div class="v204StatMini"><span>メガ</span><b data-mega>0</b></div><div class="v204StatMini"><span>構築</span><b data-build>0/6</b></div></div><div class="v204Progress"><i data-bar></i></div></div><div class="v204SideBottom"><div class="v204ThemeName" data-theme>テーマ</div>${q('settings','settings','表示設定')}</div>`;document.body.appendChild(a);a.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));a.querySelector('[data-action=savedQuick]').onclick=()=>homeUseSavedQuick();a.querySelector('[data-action=counter]').onclick=()=>homeFocusCounter();a.querySelector('[data-action=back]').onclick=()=>window.history.back();a.querySelector('[data-action=settings]').onclick=openSettings;a.querySelector('.v204Collapse').onclick=()=>{document.body.classList.toggle('v204SideMini');try{localStorage.setItem(K,document.body.classList.contains('v204SideMini')?'1':'0')}catch(e){}};refresh()}
make();const old=window.switchPage;if(typeof old==='function'){window.switchPage=function(){const r=old.apply(this,arguments);setTimeout(refresh,0);return r}};new MutationObserver(refresh).observe(document.documentElement,{attributes:true,attributeFilter:['data-app-theme']});setInterval(refresh,2500);window.__V204__={refresh,stat};
})();
</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')
