from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
marker='/* ===== v20.5 minimal rail + contrast ===== */'
if marker in s: raise SystemExit(0)
s=s.replace('Pokémon Champions Support — v20.4','Pokémon Champions Support — v20.5')
s=s.replace('Pokémon Champions Support — v20.3','Pokémon Champions Support — v20.5')
s=s.replace('<div class="badge">v20.4</div>','<div class="badge">v20.5</div>',1)
css=r'''<style id="v205-rail-style">
/* ===== v20.5 minimal rail + contrast ===== */
html[data-app-theme] body,html[data-app-theme] .page,html[data-app-theme] .card,html[data-app-theme] .teamPane,html[data-app-theme] .savedEditor,html[data-app-theme] .counterToolCard,html[data-app-theme] .pick,html[data-app-theme] .metaRec,html[data-app-theme] .v12BuildPick,html[data-app-theme] .v19IntelCard,html[data-app-theme] .v19Mini,html[data-app-theme] .v19TeamSpeed,html[data-app-theme] .mon,html[data-app-theme] .sel,html[data-app-theme] .rankRow,html[data-app-theme] .oppQuickMon,html[data-app-theme] .savedEmpty,html[data-app-theme] .dataSection,html[data-app-theme] .typeMatchSection{color:var(--xtext)!important}
html[data-app-theme] h1,html[data-app-theme] h2,html[data-app-theme] h3,html[data-app-theme] h4,html[data-app-theme] label,html[data-app-theme] b,html[data-app-theme] strong,html[data-app-theme] .pn,html[data-app-theme] .mn,html[data-app-theme] .name,html[data-app-theme] .compatPct,html[data-app-theme] .quickPct,html[data-app-theme] .completionScore,html[data-app-theme] .metaScore,html[data-app-theme] .rankNo,html[data-app-theme] .counter,html[data-app-theme] .buildMovePct,html[data-app-theme] .spreadStat .spValue,html[data-app-theme] .v19Chip strong,html[data-app-theme] .v19Speed strong{color:var(--xtext)!important}
html[data-app-theme] .small,html[data-app-theme] .sub,html[data-app-theme] .buildReasons,html[data-app-theme] .loadedSet,html[data-app-theme] .formEvidence,html[data-app-theme] .v19Muted,html[data-app-theme] .spreadStat .spLabel,html[data-app-theme] .spreadTotal{color:var(--xmuted)!important}
html[data-app-theme] input,html[data-app-theme] select,html[data-app-theme] textarea,html[data-app-theme] .savedItem,html[data-app-theme] .moveRow input,html[data-app-theme] .moveRow select,html[data-app-theme] .buildItemInput,html[data-app-theme] .buildMoveInput{background:var(--xcard2)!important;color:var(--xtext)!important;border-color:var(--xline)!important}
html[data-app-theme] input::placeholder,html[data-app-theme] textarea::placeholder{color:var(--xmuted)!important;opacity:.72}
html[data-app-theme] .moveSuggestBox,html[data-app-theme] .buildMoveSuggestBox,html[data-app-theme] .itemSuggestBox,html[data-app-theme] .counterSuggestBoxV186{background:var(--xcard)!important;color:var(--xtext)!important;border-color:var(--xline)!important}
html[data-app-theme] .missing,html[data-app-theme] .metaAnalysisStatus,html[data-app-theme] .buildMetaStatus,html[data-app-theme] .dragHandle,html[data-app-theme] .buildBreakdown span,html[data-app-theme] .v12Breakdown span,html[data-app-theme] .matchChip,html[data-app-theme] .v19Chip,html[data-app-theme] .v19Speed,html[data-app-theme] .v19CandidateTag{background:var(--xcard2)!important;color:var(--xtext)!important;border-color:var(--xline)!important}
#v204Sidebar{display:none!important}#v205Rail{display:none}
@media(min-width:1080px){body.v204HasSidebar .wrap,body.v204HasSidebar.v204SideMini .wrap,body.v205RailOn .wrap{width:auto!important;max-width:none!important;margin:0!important;padding:14px 24px 34px 104px!important}body.v205RailOn>.wrap>.appnav{display:none!important}#v205Rail{position:fixed;z-index:520;display:flex;left:14px;top:14px;bottom:14px;width:66px;padding:9px 7px;flex-direction:column;align-items:center;gap:7px;background:color-mix(in srgb,var(--xcard) 94%,transparent);border:1px solid var(--xline);border-radius:20px;box-shadow:0 12px 34px #0002;backdrop-filter:blur(14px);color:var(--xtext)}.v205Logo{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;margin-bottom:9px;background:var(--xaccent);color:var(--xaccenttext);font-weight:950;font-size:14px}.v205RailSep{width:32px;height:1px;background:var(--xline);margin-bottom:3px}.v205RailBtn{position:relative!important;width:46px!important;height:46px!important;min-height:46px!important;padding:0!important;border:0!important;border-radius:14px!important;display:grid!important;place-items:center!important;background:transparent!important;color:var(--xmuted)!important;box-shadow:none!important}.v205RailBtn:hover{background:var(--xsoft)!important;color:var(--xtext)!important}.v205RailBtn.active{background:var(--xaccent)!important;color:var(--xaccenttext)!important}.v205RailBtn svg{width:21px;height:21px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.v205Tip{position:absolute;left:56px;top:50%;transform:translateY(-50%) translateX(-3px);pointer-events:none;opacity:0;white-space:nowrap;padding:7px 9px;border-radius:9px;background:var(--xtext);color:var(--xbg);font-size:10px;font-weight:850;box-shadow:0 8px 22px #0003;transition:.12s}.v205RailBtn:hover .v205Tip{opacity:1;transform:translateY(-50%) translateX(0)}.v205Count{position:absolute;right:1px;top:1px;min-width:16px;height:16px;padding:0 4px;border-radius:999px;display:grid;place-items:center;background:var(--xtext);color:var(--xbg);font-size:8px;font-weight:950;border:2px solid var(--xcard)}.v205RailBottom{margin-top:auto;display:grid;gap:7px}#v202SettingsBtn{display:none!important}}
#partyPage{max-width:1180px;margin:0 auto}.v205PartyHead{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px!important}.v205PartyHead h2{margin:0!important;font-size:20px!important}.v205PartyActions{display:flex;gap:6px;flex-wrap:wrap}.v205PartyActions button{min-height:34px!important;padding:7px 10px!important;font-size:10px!important}.v205PartyTabs{position:sticky;top:10px;z-index:120;display:grid;grid-template-columns:1fr 1fr;gap:5px;padding:5px;margin:0 0 12px;border:1px solid var(--xline);border-radius:14px;background:color-mix(in srgb,var(--xcard) 94%,transparent);backdrop-filter:blur(12px)}.v205PartyTab{background:transparent!important;color:var(--xmuted)!important;box-shadow:none!important;min-height:38px!important}.v205PartyTab.active{background:var(--xaccent)!important;color:var(--xaccenttext)!important}.v205PartyPane{display:none}.v205PartyPane.active{display:block}#v205PartyEdit>.card:first-child{padding:12px 14px!important}#v205PartyEdit>.card:first-child h2{font-size:15px!important;margin-bottom:4px!important}#v205PartyAnalysisToolbar{display:flex;align-items:center;justify-content:space-between;gap:12px}.v205AnalysisBtns{display:flex;gap:6px;flex-wrap:wrap}#partyPage #buildCompletion{display:none!important}@media(max-width:720px){.v205PartyHead,#v205PartyAnalysisToolbar{align-items:flex-start;flex-direction:column}.v205PartyActions,.v205AnalysisBtns{width:100%}.v205PartyActions button,.v205AnalysisBtns button{flex:1}}
</style>'''
s=s.replace('</body>',css+'\n</body>',1);p.write_text(s,encoding='utf-8')
