from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8')
marker='/* ===== v20.2 original clean home ===== */'
if marker in s: raise SystemExit(0)
patch=r'''
<style>
/* ===== v20.2 original clean home ===== */
#homePage.v202Home{display:grid;gap:14px}.v202Hero{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(250px,.65fr);gap:16px;padding:22px!important}.v202Eyebrow{font-size:10px;letter-spacing:.14em;font-weight:900;color:var(--xmuted,#999);margin-bottom:5px}.v202Hero h2{font-size:clamp(27px,3.6vw,42px);line-height:1.08;margin:0 0 9px}.v202Lead{max-width:720px;line-height:1.65;color:var(--xmuted,#999)}.v202Actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.v202Ready{border:1px solid var(--xline,#444);background:var(--xcard2,#222);border-radius:16px;padding:16px;display:flex;flex-direction:column;justify-content:center}.v202ReadyScore{font-size:48px;font-weight:950;letter-spacing:-.04em}.v202Grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(300px,.85fr);gap:14px}.v202Head{display:flex;align-items:end;justify-content:space-between;gap:10px}.v202Head h2{margin:2px 0 0}.v202Party{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:7px;margin-top:12px}.v202Party .homePartyMon,.v202Party .homePartyEmpty{min-height:96px!important;background:var(--xcard2,#222)!important;border-color:var(--xline,#444)!important}.v202Party .homePartyMon img{width:64px;height:64px;image-rendering:auto!important}.v202Tools{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.v202Tools button{text-align:left;min-height:76px;padding:12px!important}.v202Tools button b{display:block;font-size:13px;margin-bottom:3px}.v202Tools button span{font-size:9px;color:var(--xmuted,#999)}.v202Meta{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:8px!important;margin-top:12px!important}.v202Meta .homeMetaMon{background:var(--xcard2,#222)!important;border-color:var(--xline,#444)!important}.v202Meta .homeMetaMon img{width:68px;height:68px;image-rendering:auto!important}.v202Stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.v202Stat{border:1px solid var(--xline,#444);background:var(--xcard,#222);border-radius:11px;padding:9px}.v202Stat strong{display:block;font-size:20px}@media(max-width:900px){.v202Hero,.v202Grid{grid-template-columns:1fr}.v202Party,.v202Meta{grid-template-columns:repeat(3,1fr)!important}}@media(max-width:520px){.v202Party,.v202Meta{grid-template-columns:repeat(2,1fr)!important}.v202Tools{grid-template-columns:1fr}}
</style>
<script>
(function(){
function build(){const h=document.getElementById('homePage');if(!h)return;h.classList.add('v202Home');h.innerHTML=`<section class="card v202Hero"><div><div class="v202Eyebrow">CHAMPIONS BATTLE DESK</div><h2>対戦前に見るものを、ここだけに。</h2><div id="homeNextText" class="v202Lead">保存状況から次の操作を整理します。</div><div class="v202Actions"><button id="homePrimaryAction" class="primary" onclick="homePrimaryAction()">おすすめの操作</button><button onclick="homeUseSavedQuick()">登録パーティで選出</button><button onclick="switchPage('build')">構築を確認</button></div></div><div class="v202Ready"><div class="small">READY</div><div id="homeSetupScore" class="v202ReadyScore">0%</div><div id="homeSetupLabel" class="small">準備状況</div><div class="compatBar"><div id="homeSetupBar" style="width:0%"></div></div><div id="v202Stats" class="v202Stats"></div></div></section><section class="v202Grid"><div class="card"><div class="v202Head"><div><div class="v202Eyebrow">MY SIX</div><h2>登録パーティ</h2></div><button onclick="switchPage('saved')">編集</button></div><div id="homePartyPreview" class="v202Party"></div><div id="homePartyHint" class="small" style="margin-top:8px"></div></div><div class="card"><div class="v202Head"><div><div class="v202Eyebrow">SHORTCUTS</div><h2>すぐ使う</h2></div></div><div class="v202Tools"><button onclick="homeUseSavedQuick()"><b>クイック選出</b><span>登録した型を使って選出</span></button><button onclick="switchPage('build')"><b>構築を改善</b><span>弱点と追加候補を見る</span></button><button onclick="homeFocusCounter()"><b>苦手対策</b><span>1体への安定回答を探す</span></button><button onclick="switchPage('env')"><b>環境データ</b><span>技・持ち物・共起を見る</span></button></div></div></section><section class="card"><div class="v202Head"><div><div class="v202Eyebrow">META NOW</div><h2>環境TOP 6</h2></div><button onclick="switchPage('env')">詳しく見る</button></div><div id="homeMetaTop" class="homeMetaTop v202Meta"></div></section>`}
function extras(){const b=document.getElementById('v202Stats');if(!b)return;const n=(savedParty||[]).length,c=(savedParty||[]).filter(m=>String(m.item||'').trim()&&(m.moves||[]).filter(x=>x?.name).length===4).length;b.innerHTML=`<div class="v202Stat"><span class="small">登録</span><strong>${n}/6</strong></div><div class="v202Stat"><span class="small">型完成</span><strong>${c}/6</strong></div>`}
build();if(typeof renderHomeV18==='function'){const old=renderHomeV18;renderHomeV18=function(){const r=old.apply(this,arguments);extras();return r};try{renderHomeV18()}catch(e){extras()}}else extras();
})();
</script>
'''
s=s.replace('</body>',patch+'\n</body>',1)
p.write_text(s,encoding='utf-8')
